/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0ULevUvFMVN
 */
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"

export function Component() {
  return (
    <div key="1" className="flex flex-col h-full w-full bg-[#f9e5d7]">
      <header className="flex justify-between items-center h-16 px-6 bg-[#333333] text-white">
        <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
          <ImageIcon className="w-6 h-6" />
          <span>StockTrade</span>
        </Link>
        <nav className="flex items-center gap-6">
          <Link className="text-white hover:text-[#0075b0]" href="#">
            Dashboard
          </Link>
          <Link className="text-white hover:text-[#0075b0]" href="#">
            Portfolio
          </Link>
          <Link className="text-white hover:text-[#0075b0]" href="#">
            Market
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Avatar className="w-8 h-8">
            <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <span>John Doe</span>
        </div>
      </header>
      <main className="flex-1 p-6 bg-[#f9e5d7]">
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 carousel">
          <Card className="bg-white">
            <CardHeader>
              <span className="text-lg font-bold text-[#333333]">AAPL</span>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div>
                <span className="text-3xl font-bold text-[#333333]">$150.30</span>
                <Badge className="ml-2 bg-green-500 text-white">+2.67%</Badge>
              </div>
              <Button className="bg-[#0075b0] text-white">Trade</Button>
            </CardContent>
          </Card>
          <Card className="bg-white">
            <CardHeader>
              <span className="text-lg font-bold text-[#333333]">GOOG</span>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div>
                <span className="text-3xl font-bold text-[#333333]">$2,805.67</span>
                <Badge className="ml-2 bg-red-500 text-white">-1.34%</Badge>
              </div>
              <Button className="bg-[#0075b0] text-white">Trade</Button>
            </CardContent>
          </Card>
          <Card className="bg-white">
            <CardHeader>
              <span className="text-lg font-bold text-[#333333]">TSLA</span>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div>
                <span className="text-3xl font-bold text-[#333333]">$688.99</span>
                <Badge className="ml-2 bg-green-500 text-white">+0.45%</Badge>
              </div>
              <Button className="bg-[#0075b0] text-white">Trade</Button>
            </CardContent>
          </Card>
        </div>
        <div className="mt-6">
          <Card className="bg-white">
            <CardHeader>
              <span className="text-lg font-bold text-[#333333]">Market Overview</span>
            </CardHeader>
            <CardContent>
              <CurvedlineChart className="w-full h-[300px]" />
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function ImageIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function CurvedlineChart(props:any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "B",
            data: [
              { x: "2018-01-01", y: 7 },
              { x: "2018-01-02", y: 5 },
              { x: "2018-01-03", y: 11 },
              { x: "2018-01-04", y: 9 },
              { x: "2018-01-05", y: 12 },
              { x: "2018-01-06", y: 16 },
              { x: "2018-01-07", y: 13 },
              { x: "2018-01-08", y: 13 },
            ],
          },
          {
            id: "A",
            data: [
              { x: "2018-01-01", y: 9 },
              { x: "2018-01-02", y: 8 },
              { x: "2018-01-03", y: 13 },
              { x: "2018-01-04", y: 6 },
              { x: "2018-01-05", y: 8 },
              { x: "2018-01-06", y: 14 },
              { x: "2018-01-07", y: 11 },
              { x: "2018-01-08", y: 12 },
            ],
          },
        ]}
        enableCrosshair={false}
        margin={{ top: 50, right: 110, bottom: 50, left: 60 }}
        xScale={{
          type: "time",
          format: "%Y-%m-%d",
          useUTC: false,
          precision: "day",
        }}
        xFormat="time:%Y-%m-%d"
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "X",
          legendOffset: 45,
          legendPosition: "middle",
          format: "%b %d",
          tickValues: "every 1 day",
        }}
        axisLeft={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Y",
          legendOffset: -45,
          legendPosition: "middle",
        }}
        colors={{ scheme: "paired" }}
        pointSize={5}
        pointColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointBorderWidth={2}
        pointBorderColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointLabelYOffset={-12}
        useMesh={true}
        curve="monotoneX"
        legends={[
          {
            anchor: "bottom-right",
            direction: "column",
            justify: false,
            translateX: 100,
            translateY: 0,
            itemsSpacing: 0,
            itemDirection: "left-to-right",
            itemWidth: 80,
            itemHeight: 20,
            symbolSize: 14,
            symbolShape: "circle",
          },
        ]}
        theme={{
          tooltip: {
            container: {
              fontSize: "12px",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
